/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ShoppingCart.module.css";

interface CartItemProps {
  image: string;
  name: string;
  price: string;
}

const CartItem: React.FC<CartItemProps> = ({ image, name, price }) => {
  return (
    <div className={styles.cartItem}>
      <div className={styles.itemDetails}>
        <img
          loading="lazy"
          src={image}
          alt={name}
          className={styles.itemImage}
        />
        <div className={styles.itemInfo}>
          <div className={styles.itemName}>{name}</div>
          <div className={styles.itemPrice}>{price}</div>
        </div>
      </div>
      <div className={styles.itemTotalPrice}>{price}</div>
    </div>
  );
};

export default CartItem;
