/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ShoppingCart.module.css";

interface OrderSummaryProps {
  subtotal: string;
  shipping: string;
  tax: string;
  total: string;
}

const OrderSummary: React.FC<OrderSummaryProps> = ({
  subtotal,
  shipping,
  tax,
  total,
}) => {
  return (
    <aside className={styles.summary}>
      <div className={styles.summaryContent}>
        <div className={styles.summaryLeft}>
          <h2 className={styles.summaryTitle}>Order summary</h2>
          <div className={styles.summaryItem}>Subtotal</div>
          <div className={styles.summaryItem}>Shipping</div>
          <div className={styles.summaryItem}>Tax</div>
          <div className={styles.summaryTotal}>Total</div>
        </div>
        <div className={styles.summaryRight}>
          <div>{subtotal}</div>
          <div className={styles.summaryPrices}>
            <div className={styles.summaryPrice}>{shipping}</div>
            <div className={styles.summaryItem}>{tax}</div>
          </div>
          <div className={styles.summaryTotal}>{total}</div>
        </div>
      </div>
      <button className={styles.summaryButton}>
        <span className={styles.buttonText}>Continue to Payment</span>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/436b738744905f60c6a542e2cd314f5694db20045d36b8991f8dab9a31b316a0?placeholderIfAbsent=true&apiKey=e2809fcf8a8249a5a890320535b1076d"
          alt=""
          className={styles.buttonIcon}
        />
      </button>
    </aside>
  );
};

export default OrderSummary;
